### PR TITLE
Add JSONMarshaler as alternative to GobMarshaler

### PR DESCRIPTION
**Pull request by ma-hartma**
To support more polyglot environments, I added a JSONMarshaler as alternative to the GobMarshaler.

I've also copied your tests and changed them to fit the JSONMarshaler.

### CODE REVIEW

**Review by AlexCuse — APPROVED** [review]
This is a good idea thanks!  It probably makes sense to offer protobuf marshaling the same way.

Also reminds me I need to fix my import grouping settings :(

**Comment by AlexCuse** [comment]
@ma-hartma I added an env var option for using this under test here: https://github.com/AlexCuse/watermill-jetstream/commit/e056002ec524f1f3a9189e08f71f02967119801d

You just need to specify the value before run eg

`WATERMILL_TEST_NATS_FORMAT=json make test`

**Comment by ma-hartma** [comment]
Thank you for building jetstream support for watermill and merging so quickly!
Good idea, I've also thought about adding the JSONMarshaler to subscriber_test and publisher_test as well. What do you think about that?

I'm currently building microservices with watermill-jetstream and will soon test it in a production environment.
If you need any help, I'd be happy to collaborate on this!

**Comment by AlexCuse** [comment]
Thanks @ma-hartma I am happy to see any and all PR's - I am not sure what there is to test in there now though, since I think it just tests for valid configuration (eg *a* marshaler is provided)?  Using JSON on the wire does make it easier to test against the watermill interfaces etc... if you wanted to add unit tests for publish / subscribe internals.

I will probably take on the protobuf marshaler at some point in the near future but if you want to knock it out have at it I don't think it will be too difficult.  Have a question in to watermill project on if they would want to include proto contracts in the `message` package but can put in here for now.

**Comment by AlexCuse** [comment]
This change is in the `v0.0.4` tag

**Pull request merged**
